version: '3.7'

services:
  nodejs:
    build: .
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - 8089:8089
    environment:
      NODE_ENV: development
    command: /usr/src/app/entrypoint.sh