version: '3.7'

services:
  nodejs:
    build: nodejs
    volumes:
      - ..:/usr/src/app
    ports:
      - 8089:8089
    environment:
      NODE_ENV: development
      PORT: 8089
    command: >
      bash -c "npm install &&
      npm run dev"

    # command: /usr/src/app/docker/nodejs/entrypoint.sh
    # command: >
    #    bash -c "npm install && 
    #     /usr/src/app/docker/nodejs/entrypoint.sh"